services:
  movecar:
    image: viklion/movecar:latest
    container_name: movecar
    restart: unless-stopped
    ports:
      - "3000:3000"             #映射端口
    environment:
      - BARK_URL=               #bark推送地址
      - PHONE_NUMBER=           #手机号
      - HIDE_PHONE_NUMBER=false #是否隐藏手机号，true:只有车主确认后才显示，false:发送通知后就显示（默认：false）
      - CAR_NUMBER=             #车牌号
      - RATE_LIMIT_5MIN=0       #相同IP在5分钟内最多发送的通知次数，0表示不限制（默认：0）
      - RATE_LIMIT_DAILY=0      #相同IP每天最多发送的通知次数，0表示不限制（默认：0）
      - RECORD_TIME=0           #IP确认记录的有效时间，单位秒，0为关闭记录功能（默认：0）
      # - ALLOWED_COUNTRIES=    #允许访问的国家代码，多个用逗号分隔 例如: CN,HK,MO,TW
      # - ENABLE_GEO_CHECK=     #启用地理位置检查 true/false